prefix sh: <http://www.w3.org/ns/shacl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
ask {
    ?nodeShapeA a sh:NodeShape ;
        sh:nodeKind sh:BlankNodeOrIRI ;
        sh:property ?data_property_str ;
        sh:targetClass <urn:test:Class> .

    ?data_property_str a sh:PropertyShape ;
        sh:datatype xsd:string ;
        sh:nodeKind sh:Literal ;
        sh:path <urn:test:data_property_str> .
}
